export const APP_TITLE="Step Up Pay and Rosters"
export const APP_BASE="/step-up"
export const API_URL="http://cofasv38/api/v1/ffd/step-up"
export const LDAP_URL="http://cofasv38/api/v1/ldap"
// export const API_URL="https://dev.franklintn.gov/api/v1/ffd/step-up"
// export const LDAP_URL="https://dev.franklintn.gov/api/v1/ldap"